## Numpy 


- eye() : 정행렬
- random.random() - 임의 값으로 행렬 생성
- reshape() - 데이터는 변경 없이 구조만 변경
- 연산 : np.add,sutract,multply,divide
- 행렬곱 : np.dot

In [3]:
import numpy as np

np_array_1 = np.array([1,2,3,4]) #--> 행렬의 형식!!
print(type(np_array_1))          

<class 'numpy.ndarray'>


In [10]:
np_array_2 = np.array([[1,2,3], [4,5,6]]) #--> 행렬의 형식!!
print((np_array_2))
print(np_array_2.ndim) #차원 수
print(np_array_2.shape) #크기 출력

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [12]:
# 0행렬 생성
zero_array = np.zeros((3,2))
print(zero_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
# 1로 채워진 행렬 생성
one_array = np.ones((3,4))
print(one_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
# np.full
full_array = np.full((4,4), 3)
print(full_array)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [15]:
#eye_array 단위행렬
eye_array = np.eye(5)
print(eye_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
random_array = np.random.random((3,3))
print(random_array)

[[0.75186115 0.03574758 0.91379967]
 [0.34834573 0.55916935 0.288244  ]
 [0.19545918 0.06199885 0.25393686]]


In [20]:
arange_array = np.arange(10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
reshape_array = arange_array.reshape((5,2))
print(reshape_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [23]:
#행렬 연산
x = np.array([1,2,3])
y = np.array([4,5,6])


In [29]:
#행렬 연산
print(x + y)
print(np.add(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.subtract(x,y))


[5 7 9]
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[-3 -3 -3]


In [30]:
# 행렬 곱
x2 = np.array([[1,2],[3,4]])
y2 = np.array([[5,6],[7,8]])


In [31]:
print(x2 @ y2)
print(np.dot(x2, y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
